<a href="https://colab.research.google.com/github/GilbertoRocha/Estudos/blob/master/FormacaoCientistaDadosPythoneR/Python/rede_neural_iris_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from yellowbrick.classifier import ConfusionMatrix
from sklearn.metrics import confusion_matrix
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

In [0]:
# carrega as info
base = datasets.load_iris()
previsores = base.data
classe = base.target

In [14]:
# cria as classes dummy para a saida.
# como tem 3 classes, serao necessarios 3 neuronios de saida, então é criado uma coluna para cada neuronio
classe_dummy = np_utils.to_categorical(classe)
print(classe_dummy)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [0]:
# separa os dados de teste
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe_dummy, test_size = 0.3, random_state = 0)

In [17]:
# cria o modelo com 5 neuronios
modelo = Sequential()
# camada de entrada
modelo.add(Dense(units= 5, input_dim = 4))
# camada escondida
modelo.add(Dense(units = 4))
# camada saida usando a softmax, sendo indicada para classificação com mais de 2 classes
modelo.add(Dense(units = 3, activation = 'softmax'))

modelo.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_8 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [20]:
# parametriz o modelo
# loss = categorical_crossentropy, calculo de custo indicado para 2 ou mais clases
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

modelo.fit(X_treinamento, y_treinamento, epochs = 1000, validation_data = (X_teste, y_teste))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 105 samples, validate on 45 samples
Epoch 1/1000





105/105 [==============================] - 1s 8ms/step - loss: 1.5910 - acc: 0.6190 - val_loss: 1.1114 - val_acc: 0.7556
Epoch 2/1000
105/105 [==============================] - 0s 137us/step - loss: 1.5072 - acc: 0.6190 - val_loss: 1.0586 - val_acc: 0.7556
Epoch 3/1000
105/105 [==============================] - 0s 121us/step - loss: 1.4254 - acc: 0.6190 - val_loss: 1.0115 - val_acc: 0.7556
Epoch 4/1000
105/105 [==============================] - 0s 107us/step - loss: 1.3504 - acc: 0.6190 - val_loss: 0.9668 - val_acc: 0.7556
Epoch 5/1000
105/105 [==============================] - 0s 104us/step - loss: 1.2715 - acc: 0.6190 - val_loss: 0.9251 - val_acc: 0.7556
Epoch 6/1000
105/105 [==============================] - 0s 106us/step - loss: 1.2041 - acc: 0.6190 - val_loss: 0.8855 - val_acc: 0.7556
Epoch 7/1000
105/105 [=================

In [24]:
previsoes = modelo.predict(X_teste)
# traz o percentual de cada classe
print(previsoes)


[[7.2550540e-14 6.9221892e-06 9.9999309e-01]
 [6.7913200e-04 9.9925774e-01 6.3155356e-05]
 [9.9997652e-01 2.3441564e-05 1.5079881e-25]
 [1.4478837e-11 1.2438537e-03 9.9875617e-01]
 [9.9974436e-01 2.5558009e-04 2.2438007e-21]
 [3.1363682e-16 4.6795378e-07 9.9999952e-01]
 [9.9983823e-01 1.6173476e-04 6.3242628e-22]
 [2.9304107e-05 9.9884039e-01 1.1303367e-03]
 [2.1424017e-05 9.9744511e-01 2.5335094e-03]
 [4.5146668e-04 9.9950004e-01 4.8438793e-05]
 [6.9644193e-09 2.4978109e-02 9.7502196e-01]
 [5.7798024e-05 9.9940550e-01 5.3670537e-04]
 [4.5037923e-05 9.9781978e-01 2.1351890e-03]
 [2.0506666e-05 9.9327749e-01 6.7019630e-03]
 [1.8315897e-05 9.8757172e-01 1.2409862e-02]
 [9.9992311e-01 7.6898366e-05 5.1219767e-23]
 [2.1671256e-05 9.8546696e-01 1.4511489e-02]
 [5.5860553e-05 9.9091107e-01 9.0331268e-03]
 [9.9925548e-01 7.4447220e-04 2.1814301e-19]
 [9.9991238e-01 8.7587396e-05 2.2896953e-23]
 [2.1556926e-10 1.3217126e-03 9.9867827e-01]
 [1.6621800e-05 9.5847821e-01 4.1505221e-02]
 [9.984051

In [26]:
# atribui a classe que tiver mais de 50% de chance
previsoes = (previsoes > 0.5)
print(previsoes)

[[False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]]


In [31]:
# verifica a precisao
#pega somente o index do atributo (indicando a classe)
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
print(confusao)


[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
