<a href="https://colab.research.google.com/github/GilbertoRocha/Estudos/blob/master/FormacaoCientistaDadosPythoneR/Python/Agrupamento_Fuzzy_C_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
%pip install scikit-fuzzy

     |████████████████████████████████| 1.0MB 2.7MB/s 
  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-cp36-none-any.whl size=894070 sha256=fb1c1f718ff724b167fc8bf388a84caea5807118f76143481760963df9e084fa
  Stored in directory: /root/.cache/pip/wheels/b9/4e/77/da79b16f64ef1738d95486e2731eea09d73e90a72465096600
Successfully built scikit-fuzzy


In [0]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
import skfuzzy

In [0]:
iris = datasets.load_iris()

In [0]:
# cria o cluster (no caso do iris.data, e usado o metodo T para transpor a matriz, trocando linhas e colunas)
# c = numero de cluster
# m = membership, ou seja a qual grupo cada cluster pertence (default 2)
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005, maxiter= 1000, init=None)

In [15]:
# converte as previsoes
previsoes_porcentagem = r[1]
print(previsoes_porcentagem[0][0])
print(previsoes_porcentagem[1][0])
print(previsoes_porcentagem[2][0])

# pega o indice do maior valor de porcentagem
previsoes = previsoes_porcentagem.argmax(axis=0)
print(previsoes)

resultados = confusion_matrix(iris.target, previsoes)
print(resultados)

0.0023044388819177457
0.0010719290703744798
0.9966236320477079
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 1
 1 0]
[[ 0  0 50]
 [47  3  0]
 [13 37  0]]
